ProyectoGeolocalizacion/ProyectoGeolocalizacion/Controllers/HeatMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoGeolocalizacion.Data;
using ProyectoGeolocalizacion.Models;

namespace ProyectoGeolocalizacion.Controllers
{
    public class HeatMapController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HeatMapController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string alias, string canal)
        {

            ViewData["alias"] = alias;
            ViewData["canal"] = canal;
            if (alias != null)
            {
                var device = await _context.Device.Where(x => x.Alias == alias).FirstOrDefaultAsync();
                var channel = await _context.Channel.Where(x => x.Name == canal).FirstOrDefaultAsync();


                List<Location> locations = await _context.Location.Where(x => x.DeviceId == device.Id).ToListAsync();
                return View(locations);

            }
            var allLocations = await _context.Location.ToListAsync();

            return View(allLocations);
        }
    }
}

ProyectoGeolocalizacion/ProyectoGeolocalizacion/Controllers/MapsHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoGeolocalizacion.Data;
using ProyectoGeolocalizacion.Models;

namespace ProyectoGeolocalizacion.Controllers
{
    public class MapsHomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MapsHomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string alias, string canal)
        {

            var device = await _context.Device.FirstOrDefaultAsync(x => x.Alias == alias);
            ViewData["alias"]=alias;
            ViewData["channel"] = canal;

            return View();
        }
    }
}

ProyectoGeolocalizacion/ProyectoGeolocalizacion/Controllers/MapsPositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoGeolocalizacion.Data;

namespace ProyectoGeolocalizacion.Controllers
{
    public class MapsPositionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MapsPositionController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string alias, string canal)
        {
            if (alias != null)
            {
                var device = await _context.Device.Where(x => x.Alias == alias).FirstOrDefaultAsync();
                device.Status = "Online";
                device.Channel = canal;
                _context.Update(device);
                await _context.SaveChangesAsync();
            }


            var devices = await _context.Device.Where(x => x.Status == "Online").Where(x => x.Channel == canal).ToListAsync();
            ViewData["alias"] = alias;
            ViewData["canal"] = canal;
            return View(devices);
        }

        public async Task<IActionResult> DeviceOff(string alias, string canal)
        {
            if (alias != null)
            {
                var device = await _context.Device.Where(x => x.Alias == alias).Where(x => x.Channel == canal).FirstOrDefaultAsync();
                if (device.Status == "Online")
                {
                    device.Status = "Offline";
                    device.Channel = null;
                    _context.Update(device);
                    await _context.SaveChangesAsync();

                }
            }

            var devices = await _context.Device.Where(x => x.Status == "Online").Where(x => x.Channel == canal).ToListAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ProyectoGeolocalizacion/ProyectoGeolocalizacion/Views/MapsHome/Index.cshtml
@{
    ViewData["Title"] = "Index";
    string alias = (string)ViewData["alias"];
    string canal = (string)ViewData["channel"];
}



<div class="alert alert-success" role="alert">

    <h4 class="alert-heading text-center">¡Has entrado al canal: @ViewData["channel"]!</h4>


</div>
<div class="row">
    <div class="offset-1"> <h4>Selecciona el mapa que quieres visualizar:</h4></div>
   
</div>

<div class="row">
    <div class="card-container col-md-4 mt-4">
        <div class="card mb-4 border-dark">
            <img class="card-img-top foto zoom" src="https://camo.githubusercontent.com/a0281bc5c0b55f8175fd3ed18c972b320c60e254/68747470733a2f2f7261772e6769746875622e636f6d2f6c766f6f6764742f4c6561666c65742e617765736f6d652d6d61726b6572732f6d61737465722f73637265656e73686f74732f73637265656e73686f742d736f66742e706e67" alt="Card image cap">
            <div class="card-body text-center">
                <h4 class="card-title">Mapa de posición</h4>
                <p>Descubre dónde se encuentran las personas conectadas a ese canal.</p>
                <a type="button" class="btn btn-dark btn-sm" asp-area="" asp-controller="MapsPosition" asp-action="Index" asp-route-alias="@alias" asp-route-canal="@canal">Acceder</a>
            </div>
        </div>
    </div>
    <div class="card-container col-md-4 mt-4">
        <div class="card mb-4 border-dark">
            <img class="card-img-top foto zoom" src="https://user-images.githubusercontent.com/11360512/38074134-8cb8495a-334f-11e8-94e1-8738337ba16f.png" alt="Card image cap">
            <div class="card-body text-center">
                <h4 class="card-title">Ruta</h4>
                <p>Obtén las rutas de los dispositivos del canal.</p>
                <a type="button" class="btn btn-dark btn-sm" asp-area="" asp-controller="MapsRoutes" asp-action="Index" asp-route-alias="@alias" asp-route-canal="@canal">Acceder</a>
            </div>
        </div>
    </div>
    <div class="card-container col-md-4 mt-4">
        <div class="card mb-4 border-dark">
            <img class="card-img-top foto zoom" src="https://assets.dmagstatic.com/wp-content/uploads/2019/05/dallas_mayor_2019_early_voting-heatmap.jpg" alt="Card image cap">
            <div class="card-body text-center">
                <h4 class="card-title">Calor</h4>
                <p>¿Por dónde han estado? Mapa que muestra los movimientos de los dispositivos.</p>
                <a type="button" class="btn btn-dark btn-sm" asp-area="" asp-controller="HeatMap" asp-action="Index" asp-route-alias="@alias" asp-route-canal="@canal">Acceder</a>
            </div>
        </div>
    </div>
</div>